

/* Create Tables */

CREATE TABLE BLACK_COMPANY
(
	BLACK_COMPANY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ブラック企業ID',
	BLACK_COMPANY_NAME VARCHAR(128) NOT NULL COMMENT 'ブラック企業名',
	AGENT_COMPANY_NAME VARCHAR(128) COMMENT '営業代行会社名 : 契約企業名と違う名称で　営業代行会社として利用する場合には設定する。
未設定の場合は契約企業名を営業代行会社名として使用する。',
	ZIP_CODE VARCHAR(32) NOT NULL COMMENT '郵便番号 : 基本的に半角数字＋ハイフン。日本語文字列が入ってしまっている場合がある。',
	ADDRESS1 VARCHAR(1024) NOT NULL COMMENT '住所1',
	ADDRESS2 VARCHAR(1024) COMMENT '住所2',
	BLACK_COMPANY_STATUS_CD CHAR(3) NOT NULL COMMENT 'ブラック企業ステータスコード',
	INS_DATETIME DATETIME NOT NULL COMMENT 'insert日時',
	UPD_DATETIME DATETIME NOT NULL COMMENT 'UPD_DATETIME',
	INS_TRACE VARCHAR(256) NOT NULL COMMENT 'Insertトレース',
	UPD_TRACE VARCHAR(256) NOT NULL COMMENT 'UPD トレース',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (BLACK_COMPANY_ID)
) COMMENT = 'ブラック企業(黒い企業) : 取引先のブラックな企業。
ブラックブランドとしてブラックさに磨きをかけるよう提案する。';


CREATE TABLE CLS_BLACK_COMPANY_STATUS
(
	BLACK_COMPANY_STATUS_CD CHAR(3) NOT NULL COMMENT 'ブラック企業ステータスコード',
	CODE_NAME VARCHAR(30) NOT NULL COMMENT '区分値識別名',
	CODE_ALIAS VARCHAR(50) NOT NULL COMMENT '区分値表示名',
	CODE_DISPLAY_NO INT NOT NULL COMMENT '区分値表示順',
	CODE_COMMENT VARCHAR(256) NOT NULL COMMENT '区分値コメント',
	CODE_ALIAS_EN VARCHAR(50) NOT NULL COMMENT '区分値表示名（英語）',
	PRIMARY KEY (BLACK_COMPANY_STATUS_CD)
) COMMENT = '[区分値]ブラック企業ステータス';



/* Create Foreign Keys */

ALTER TABLE BLACK_COMPANY
	ADD FOREIGN KEY (BLACK_COMPANY_STATUS_CD)
	REFERENCES CLS_BLACK_COMPANY_STATUS (BLACK_COMPANY_STATUS_CD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



