

/* Create Tables */

CREATE TABLE LOGIN
(
	LOGIN_ID INT NOT NULL COMMENT 'ログインID : ログインした瞬間のID
',
	LOGIN_DATETIME DATETIME NOT NULL COMMENT 'ログイン日時',
	MEMBER_ID INT(100) NOT NULL COMMENT '会員ID : 会員のID
',
	PRIMARY KEY (LOGIN_ID)
) COMMENT = 'ログイン';


CREATE TABLE MEMBER
(
	MEMBER_ID INT(100) NOT NULL UNIQUE COMMENT '会員ID : 会員のID
',
	EMAIL_ADDRESS VARCHAR(100) NOT NULL UNIQUE COMMENT 'メールアドレス : 会員のメールアドレス',
	USER_NAME VARCHAR(50) NOT NULL COMMENT '会員ユーザ名 : 会員のユーザ名',
	UPDATE_DATETIME DATETIME COMMENT '更新日時',
	BIRTHDATE DATE COMMENT '生年月日 : 会員の生年月日',
	PROFILE VARCHAR(200) COMMENT 'プロフィール',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = '会員';


CREATE TABLE MEMBER_SECURITY
(
	MEMBER_ID INT(100) NOT NULL UNIQUE COMMENT '会員ID : 会員のID
',
	PASSWORD VARCHAR(50) NOT NULL COMMENT 'パスワード',
	PASSWORD_REGESTERATION_DATETIME DATETIME NOT NULL COMMENT 'パスワード登録日時',
	PASSWORD_UPDATE_DATETIME DATETIME COMMENT 'パスワード更新日時',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = '会員セキュリティ';


CREATE TABLE MEMBER_WITHDRAW
(
	WITHDRAWAL_REASON_ID INT COMMENT '退会理由ID : 会員の退会理由ID',
	MEMBER_ID INT(100) NOT NULL UNIQUE COMMENT '会員ID : 会員のID
',
	WITHDRAWAL_REASON_INPUT_TEXT TEXT COMMENT '退会理由入力テキスト',
	WITHDRAWAL_DATETIME DATETIME NOT NULL COMMENT 'withdrawal_datetime : 退会日時',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = '会員退会';


CREATE TABLE TWEET
(
	TWEET_ID INT NOT NULL UNIQUE COMMENT 'TWEET_ID',
	MEMBER_ID INT(100) NOT NULL COMMENT '会員ID : 会員のID
',
	TWEET VARCHAR(140) NOT NULL COMMENT 'TWEET',
	TWEET_DATETIME DATETIME NOT NULL COMMENT 'TWEET日時',
	PRIMARY KEY (TWEET_ID)
) COMMENT = 'TWEET';



/* Create Foreign Keys */

ALTER TABLE LOGIN
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_SECURITY
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_WITHDRAW
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



